### ISSUE TITLE
Calibre crashes on startup

### ISSUE THREAD

**Issue by christann404** [OpenMandrivaAssociation/distribution#2884]
**OpenMandriva version**:

**Describe the bug**:

**Steps to reproduce**:

**Observed behavior**:

**Expected behavior**:

**Additional comment**:

**Logs and screenshots if relevant**

**Comment by christann404** [comment]
I am running Cooker. When I try to start up calibre, I get:
calibre
Failed to import PyQt module: PyQt6.QtNetwork with error: /usr/lib64/python3.11/site-packages/PyQt6/QtNetwork.abi3.so: undefined symbol: _ZN16QNetworkDatagram7destroyEP23QNetworkDatagramPrivate, version Qt_6
Traceback (most recent call last):
  File "/usr/bin/calibre", line 21, in <module>
    sys.exit(calibre())
             ^^^^^^^^^
  File "/usr/lib64/calibre/calibre/gui_launch.py", line 71, in calibre
    from calibre.gui2.main import main
  File "/usr/lib64/calibre/calibre/gui2/__init__.py", line 13, in <module>
    from qt.core import (
ImportError: cannot import name 'QNetworkProxyFactory' from 'qt.core' (/usr/lib64/calibre/qt/core.py)


[omdv-bug-report-20230327104220.log](https://github.com/OpenMandrivaAssociation/distribution/files/11079901/omdv-bug-report-20230327104220.log)

**Comment by christann404** [comment]
April 24: It now works on an up-to-date cooker. This issue can be closed.
